### ISSUE TITLE
Pulse Experiment Feature Requests

### ISSUE THREAD

**Issue by BB720** [knowm/memristor-discovery#1]
Hi.
I am glad to use the memristor-discovery software with memristor-discovery kit . I have few requests to access further potential of the software.
1. higher pulse number: Sometimes the memristor may not trigger with 10 pulses (may take 100 or more pulses). So its always useful to have higher pulse  numbers. 
2. independent pulse interval: currently pulse interval depends on pulse width. Many a time to understand memory behavior,  its important to have independent control on pulse width and pulse interval (interval may range up to seconds). 
3. Pulse width range: Depending on the memristor, Pulse width may range from microseconds to milliseconds. So its very useful to have up to few hundreds of millisecond range for pulse width. 
4. sample rate: memory decay is another important factor in memristor. This may happen in micro to millisecond ranges too. So its highly useful to have sample rate range extended to less than 1 s.  
5. Voltage range: Again depending on the memristor type, some may require higher voltage strength to trigger. So its useful to have extended voltage range. 
I am very much hoping to see these additions to the software. 

Thank you

**Comment by timmolter** [comment]
I will add this in a future release. Thanks for the suggestions!
