### ISSUE TITLE
AD2 Power Toggling Bug

### ISSUE THREAD

**Issue by alex-nugent** [knowm/memristor-discovery#3]
User with a Windows 10 install has experienced a bug whereby the +V/-V pins, which power the MD board via AD2, toggle between +-5V and +-2V. This occurred prior to and after 0.0.7 release. No other reports of this issue and currently unclear if it is a Windows 10 issue or specific to user install.

**Comment by timmolter** [comment]
I tried to replicate the issue on Windows 10 with the latest software (develop) and could not replicate the issue.
